🟣 Update: 2021-05-14 @ 09:30:26

diff --git a/mac_dotfiles/zshrc b/mac_dotfiles/zshrc
--- a/mac_dotfiles/zshrc
+++ b/mac_dotfiles/zshrc
@@ -136,32 +136,64 @@ if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
 
 # Deploying to staging via Argo.
 argo-deploy-stage(){
-        kubeconfig-stage
-        ./scripts/deploy.sh staging
+  kubeconfig-stage
+  ./scripts/deploy.sh staging
+}
+
+# Builds and deploys a local branch to staging.
+argo-deploy-stage-local() {
+  kubeconfig-stage
+
+  currentRev=$(git describe --always)
+  repo=$(basename `git rev-parse --show-toplevel`)
+  commitMessage=$(git log -1 --pretty=%B)
+
+  imageTag="${1}"
+
+  if [ -z "$imageTag" ]; then
+	   imageTag="git-$(git describe --always)" \
+		   || error "Could not get git revision"
+  fi
+
+  printf "****************************************************\n"
+  printf "~~Deploying revision:~~\n"
+  printf "$currentRev\n"
+  printf "$commitMessage\n"
+  printf "\n~~Deploying to service:~~\n"
+  printf "$repo\n"
+  printf "\n~~Deploying ecr image:~~\n"
+  printf "$imageTag\n"
+  printf "****************************************************\n"
+
+  gradle clean build
+  saml2aws exec --exec-profile monolith -- ./scripts/ecr.sh $repo $currentRev
+
+  ./scripts/deploy.sh staging $imageTag
+
 }
 
 # Deploying to production via Argo.
 argo-deploy-prod(){
-        kubeconfig-prod
-        ./scripts/deploy.sh production
+  kubeconfig-prod
+  ./scripts/deploy.sh production
 }
 
 # Setting Kubernetes config to Production.
 kubeconfig-prod(){
-        export KUBECONFIG=~/.kube/barrel
+  export KUBECONFIG=~/.kube/barrel
 }
 
 # Setting Kubernetes config to Staging.
 kubeconfig-stage(){
-        export KUBECONFIG=~/.kube/apollo
+  export KUBECONFIG=~/.kube/apollo
 }
 
 # Docker is being annoying, let's just burn it to the ground.
 murderdocker() {
-    docker volume prune
-    docker container prune --filter "until=24h"
-    docker image prune -a --filter "until=24h"
-    docker network prune
+  docker volume prune
+  docker container prune --filter "until=24h"
+  docker image prune -a --filter "until=24h"
+  docker network prune
 }
 
 # Create a new directory and enter it
